---
apiVersion: v1
kind: ReplicationController
metadata:
  name: ratesdb-sql-controller
  namespace: handknitted
spec:
  replicas: 1
  selector:
    app: ratesdb-mysql
  template:
    metadata:
      labels:
        app: ratesdb-mysql
    spec:
      containers:
      - name: ratesdb-mysql
        image: mysql:5.5
        ports:
        - containerPort: 3306
          name: ratesdb-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "secretmysql"
        - name: MYSQL_DATABASE
          value: "ratesdb"
        volumeMounts:
        - name: sql-volume
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: sql-volume
        configMap:
          name: ratesdb-mysql-config
