apiVersion: v1
kind: ConfigMap
metadata:
  namespace: handknitted
  name: ratesdb-mysql-config
data:
  ratesdb.sql: |
    CREATE DATABASE IF NOT EXISTS `ratesdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    USE `ratesdb`;

    SET foreign_key_checks = 0;

    CREATE TABLE IF NOT EXISTS `rates` (
          `rateID` VARCHAR(36) NOT NULL,
          `rateCardID` VARCHAR(36) NULL,
          `region` VARCHAR(128) NOT NULL,
          `meterID` VARCHAR(128) NOT NULL,
          `name` VARCHAR(128) NOT NULL,
          `effectiveDate` DATE NOT NULL,
          `rate` DECIMAL(21, 20) NULL,
          `unit` VARCHAR(128) NOT NULL,
          `status` VARCHAR(16) NULL,
          `createdDateTime` DATETIME(3) NOT NULL,
          `deletedDateTime` DATETIME(3) NULL,
          PRIMARY KEY (`rateID`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

    CREATE TABLE IF NOT EXISTS `rate_cards` (
          `rateCardID` VARCHAR(36) NOT NULL,
          `provider` VARCHAR(36) NOT NULL,
          `createdDateTime` DATETIME(3) NOT NULL,
          PRIMARY KEY (`rateCardID`),
          UNIQUE KEY (`provider`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

    GRANT ALL ON ratesdb.* TO 'cost-analytics'@'%' IDENTIFIED BY 'password';

    GRANT ALL ON ratesdb.* TO 'cost-analytics'@'localhost' IDENTIFIED BY 'password';
